/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lua_commons_impl_nativelua_NativeLuaStateApi */

#ifndef _Included_org_lua_commons_impl_nativelua_NativeLuaStateApi
#define _Included_org_lua_commons_impl_nativelua_NativeLuaStateApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _getenvironment
 * Signature: ()Lorg/lua/commons/impl/nativelua/NativeLuaEnvironment;
 */
JNIEXPORT jobject JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1getenvironment
  (JNIEnv *, jobject);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _isnil
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1isnil
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _isnone
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1isnone
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _isnoneornil
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1isnoneornil
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _isboolean
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1isboolean
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _isnumber
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1isnumber
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _isintegerx
 * Signature: (JIII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1isintegerx
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _isstring
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1isstring
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _isfunction
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1isfunction
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _istable
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1istable
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _isthread
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1isthread
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _isuserdata
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1isuserdata
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _isjfunction
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1isjfunction
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _isobjectx
 * Signature: (JILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1isobjectx
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _pushnil
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1pushnil
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _pushboolean
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1pushboolean
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _pushinteger
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1pushinteger
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _pushnumber
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1pushnumber
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _pushstring
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1pushstring
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _pushobject
 * Signature: (JLjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1pushobject
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _pushjclosure
 * Signature: (JLjava/lang/Object;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1pushjclosure
  (JNIEnv *, jobject, jlong, jobject, jstring, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _pushthread
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1pushthread
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _toboolean
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1toboolean
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _tointeger
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1tointeger
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _tonumber
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1tonumber
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _tostring
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1tostring
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _toobject
 * Signature: (JI)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1toobject
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _tothread
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1tothread
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _pop
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1pop
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _pushvalue
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1pushvalue
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _gettop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1gettop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _settop
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1settop
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _copy
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1copy
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _insert
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1insert
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _remove
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1remove
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _replace
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1replace
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _type
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1type
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _typename
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1typename
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _checkstack
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1checkstack
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _absindex
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1absindex
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _arith
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1arith
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _compare
 * Signature: (JIII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1compare
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _concat
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1concat
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _Lnewstate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1Lnewstate
  (JNIEnv *, jobject);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _Ldofile
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1Ldofile
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _Ldostring
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1Ldostring
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _newthread
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1newthread
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _Lopenlibs0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1Lopenlibs0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _Lloadfile
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1Lloadfile
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _Lloadstring
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1Lloadstring
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _getglobal
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1getglobal
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _setglobal
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1setglobal
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _createtable
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1createtable
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _gettable
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1gettable
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _settable
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1settable
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _getfield
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1getfield
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _setfield
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1setfield
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _next
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1next
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _rawget
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1rawget
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _rawset
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1rawset
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _rawgeti
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1rawgeti
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _rawseti
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1rawseti
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _Lref
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1Lref
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _Lunref
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1Lunref
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _rawequal
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1rawequal
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _getmetatable
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1getmetatable
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _setmetatable
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1setmetatable
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _getuservalue
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1getuservalue
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _setuservalue
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1setuservalue
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _call
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1call
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _pcall
 * Signature: (JIII)I
 */
JNIEXPORT jint JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1pcall
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _callk
 * Signature: (JIILjava/lang/Object;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1callk
  (JNIEnv *, jobject, jlong, jint, jint, jobject, jstring);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _pcallk
 * Signature: (JIIILjava/lang/Object;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1pcallk
  (JNIEnv *, jobject, jlong, jint, jint, jint, jobject, jstring);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _yield
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1yield
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _yieldk
 * Signature: (JILjava/lang/Object;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1yieldk
  (JNIEnv *, jobject, jlong, jint, jobject, jstring);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _resume
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1resume
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _getctxstate
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1getctxstate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _status
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1status
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _version
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1version
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _len
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1len
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _rawlen
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1rawlen
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _error
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1error
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _Ltypename
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1Ltypename
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _Lwhere
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1Lwhere
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _upvalueindex
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1upvalueindex
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _dump
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1dump
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _Lloadbuffer
 * Signature: (J[BLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1Lloadbuffer
  (JNIEnv *, jobject, jlong, jbyteArray, jstring);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _getupvalue
 * Signature: (JII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1getupvalue
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     org_lua_commons_impl_nativelua_NativeLuaStateApi
 * Method:    _setupvalue
 * Signature: (JII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_lua_commons_impl_nativelua_NativeLuaStateApi__1setupvalue
  (JNIEnv *, jobject, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
